source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'github-linguist'
gem 'rinku'
# gem 'escape_utils'
gem 'email_reply_parser'
gem 'gemoji'
gem 'github-markdown'
gem 'escape_utils'
gem 'sanitize'
